services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-thinkdodb}
      POSTGRES_USER: ${POSTGRES_USER:-thinkdouser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-thinkdopassword}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-thinkdouser} -d ${POSTGRES_DB:-thinkdopassword}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  app-api:
    restart: always
    container_name: app-api
    image: localhost:5000/backend:latest
    environment:
      ConnectionStrings__DefaultConnection: ${CONNECTION_STRING:-Host=postgres;Port=5432;Database=thinkdodb;Username=thinkdouser;Password=thinkdopassword}
      ASPNETCORE_URLS: http://+:8081
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://app-api:8081/health || exit 1" ]
      interval: 10s
      timeout: 20s
      retries: 10
      start_period: 120s
    networks:
      - app-network

  web:
    restart: always
    container_name: web
    image: localhost:5000/frontend:latest
    environment:
      SPRING_PROFILES_ACTIVE: production
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-Ov23lidbxnx4ozM8EsfW}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-e047c3267b4c9bd12ecb160f6c7a0896ed274044}
      API_BASE_URL: http://app-api:8081
    ports:
      - "8080:8080"
    depends_on:
      app-api:
        condition: service_healthy
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
