name: CI Pipeline

# ТРИГГЕРЫ:
on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'web/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'web/**'

jobs:
  # СБОРКА БЭКЕНДА
  build-backend:
    name: Backend Check (.NET 8)
    runs-on: ubuntu-latest

    steps:
      # КЛОНИРОВАНИЕ:
      - name: Checkout code
        uses: actions/checkout@v4

      # ОКРУЖЕНИЕ:
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # КЕШИРОВАНИЕ: (Сохраняем NuGet-пакеты, чтобы следующая сборка была быстрее)
      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('server/**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      # RESTORE:
      - name: Restore dependencies
        run: dotnet restore server/server.sln

      # BUILD:
      # Если Common не соберется, API тоже упадут
      - name: Build projects
        run: dotnet build server/server.sln --configuration Release --no-restore

      # TEST:
      - name: Run tests
        run: dotnet test server/server.sln --configuration Release --no-build --verbosity normal

# СБОРКА ФРОНТЕНДА
  build-frontend:
    name: Frontend Check (Java 17)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Сборка через Maven
      - name: Build with Maven
        if: hashFiles('web/pom.xml') != ''
        working-directory: ./web
        run: ./mvnw clean package

      # Сборка через Gradle
      - name: Build with Gradle
        if: hashFiles('web/build.gradle') != ''
        working-directory: ./web
        run: |
          chmod +x gradlew
          ./gradlew build